### ISSUE TITLE
Register domain chaos-unicorn-day.org

### ISSUE THREAD

**Issue by oskarth** [status-im/chaos-unicorn-day#2]
Register domain and redirect

cc @jakubgs could you help with this?

**Comment by jakubgs** [comment]
Sure, but I will have to get access to our Gandi account.

**Comment by oskarth** [comment]
Do you know who has it?

**Comment by jakubgs** [comment]
I'm poked a few people, we'll see. I haven't touched Gandi pretty much since I joined Status.
What is the deadline on this?

**Comment by jakubgs** [comment]
Okay, I've registered `chaos-unicorn-day.org` with Gandi DNS Registrar. What's next?

**Comment by oskarth** [comment]
Cheers! I think there should be an option in GH pages to set CNAME/domain etc. https://help.github.com/articles/using-a-custom-domain-with-github-pages/

Deadline: no specific but it'd help to have a nice URL to get people to participate early

<blockquote><div><strong><a href="https://help.github.com/articles/using-a-custom-domain-with-github-pages/">Using a custom domain with GitHub Pages - User Documentation</a></strong></div><div>You can customize the domain name of your GitHub Pages site.
…</div></blockquote>

**Comment by jakubgs** [comment]
Okay, I'll set it up today.

**Comment by jakubgs** [comment]
https://github.com/status-im/chaos-unicorn-day - is this the repo you want to host?

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/chaos-unicorn-day">status-im/chaos-unicorn-day</a></strong></div><div>Contribute to status-im/chaos-unicorn-day development by creating an account on GitHub.</div></blockquote>

**Comment by jakubgs** [comment]
https://chaos-unicorn-day.org/ - there you go.

<blockquote><div>chaos-unicorn-day</div><div><strong><a href="http://chaos-unicorn-day.org/">Chaos Unicorn Day, April 1 2019 (aka kill our cluster)</a></strong></div></blockquote>

**Comment by oskarth** [comment]
Cheers!
